name: porsche_challenge
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - python-dotenv
  - ipykernel
  - setuptools
  - wheel
  - pip
  - pip:
      - beautifulsoup4
      - beautifulsoup4
      - bitsandbytes
      - faiss-cpu
      - huggingface-hub
      - langchain
      - langchain-anthropic
      - langchain-aws
      - langchain-community
      - langchain-core
      - langchain-huggingface
      - langchain-openai
      - langchain-text-splitters
      - openai
      - peft
      - playwright
      - playwright
      - pypdf
      - pypdfium2
      - sentence-transformers
      - sentence-transformers
      - transformers
      - xformers
